import Head from 'next/head'
import Image from 'next/image'
import { useForm } from "react-hook-form";
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login EMAJ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.telaHome}>
        <div className={styles.bodyHome}>
          <div className={styles.navLateral}>
            <h2 className={styles.navTitulo}>EMAJ</h2>
            <hr></hr>
            <br />
            <button>Botão 1</button>
            <button>Botão 2</button>
            <button>Botão 3</button>
            <button>Botão 4</button>
            <button className={styles.btnSair}>Sair</button>
          </div>
          <div className={styles.board}>
            <div className={styles.conteudo}>
              <h1>Bem vindo</h1>
            </div>
            <footer className={styles.footer}>
              <h4>NIU</h4>
            </footer>
          </div>
        </div>

      </main >
    </div >
  )
}
