import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useForm } from "react-hook-form";
import styles from '../styles/Home.module.css'

function exibirInput(num) {

  if (typeof document !== 'undefined') {
    var senha = document.getElementById("DivSenha");
    var codigo = document.getElementById("DivCod");
    senha.hidden = true;
    codigo.hidden = true;

    switch (num) {

      case 1:
        senha.hidden = false;
        codigo.hidden = true;
        return

      case 2:
        senha.hidden = true;
        codigo.hidden = false;
        return
    }
  }
}

function exibeErro(msg){
  document.getElementById("erro").innerHTML = msg.response.data.error
  return msg
}

async function login(body) {

  var raAluno = body.ra
  var retorno = await axios.post(process.env.BACKEND + "aluno/login", {
    'ra': raAluno
  }).then(response  => {}).catch((error) => exibeErro(error)) 

  console.log(retorno)

    if(retorno == undefined){
      console.log("retorno undefined")
      return
    }else{
      console.log("2")
    }

    var primeiroLogin = retorno.data.usuario.primeiro_login;
    if (primeiroLogin === 1) {
      exibirInput(2);
      if (body.NPassword === body.NrePassword) {
        var validaCodigo = await axios.post(process.env.BACKEND + "aluno/register", {
          'codigo_validacao': body.cod,
          'senha': body.NPassword
        })
      }
    } else {
      exibirInput(1);
    }
  
}

export default function Home() {
  const { register, handleSubmit } = useForm()
  return (
    <div className={styles.container}>
      <Head>
        <title>Login EMAJ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.telaLogin}>
        <div className={styles.imagemLogin}>
        </div>
        <div className={styles.formLogin}>
          <h1 className={styles.tituloLogin}>LOGIN</h1>
          <form className={styles.formulario} onSubmit={handleSubmit(login)}>
            <label>Matricula</label><br />
            <input className={styles.inputLogin} name="ra" {...register("ra")} required></input>
            {exibirInput(0)}
            <div id="DivSenha" hidden>
              <label>Senha</label><br />
              <input className={styles.inputLogin} type="password" name="password" {...register("password")}></input>
            </div>
            <div id="DivCod" hidden>
              <label>Codigo</label><br />
              <input className={styles.inputLogin} name="cod" {...register("cod")}></input>
              <span>Um codigo de confirmação foi enviado para seu email.</span>
              <br />
              <label>Criar senha</label><br />
              <input className={styles.inputLogin} name="senha" {...register("NPassword")}></input>
              <label>Repita a senha</label><br />
              <input className={styles.inputLogin} name="reSenha" {...register("NrePassword")}></input>
            </div>
            <p id="erro">
            </p>
            <button type="submit" className={styles.btnLoginavancar}>Avançar</button>
          </form>
          <footer className={styles.footer}>
            <h4>NIU</h4>
          </footer>
        </div>
      </main>
    </div>
  )
}
